monolog:
    channels: ['easycredit']
    handlers:
        easycredit:
            type: rotating_file
            path: "%kernel.logs_dir%/netzkollektiv_easycredit.log"
            level: debug
            channels: [ 'easycredit' ]